project_id             = "caprivax-prod-platform-infra" # Ensure this project exists!
environment            = "prod"
region                 = "us-central1"
zone                   = "us-central1-c"
vpc_cidr               = "10.100.2.0/24"
jenkins_machine_type   = "e2-standard-4"
enable_public_ip       = false
enable_preemptible     = false
automatic_restart      = true
